[Settings]
# Added automatically by the Netlify CLI. It has no effect during normal
# Git-backed deploys.
ID = "Your_Site_ID"

# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  base = ""
  publish = "site/"
  command = "mkdocs build"

[build.environment]
  PYTHON_VERSION = "3.8"

[[redirects]]
  from = "/expressions/exceptions.html"
  to = "/expressions/errors.html"
  status = 301
  force = true

[[redirects]]
  from = "/capabilities.html"
  to = "/reference-capabilities.html"
  status = 301
  force = true

[[redirects]]
  from = "/capabilities/object-capabilities.html"
  to = "/object-capabilities.html"
  status = 301
  force = true

[[redirects]]
  from = "/capabilities/trust-boundary.html"
  to = "/object-capabilities/trust-boundary.html"
  status = 301
  force = true

[[redirects]]
  from = "/capabilities/*"
  to = "/reference-capabilities/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/pattern-matching/index.html"
  to = "/expressions/match.html"
  status = 301
  force = true

[[redirects]]
  from = "/pattern-matching/match.html"
  to = "/expressions/match.html"
  status = 301
  force = true

[[redirects]]
  from = "/pattern-matching/as.html"
  to = "/expressions/as.html"
  status = 301
  force = true
