definitions:
  - &page_title_with_site_name >-
    {% set title = config.site_name %}
    {% if page and page.parent is not none %}
      {% set title = page.parent.title ~ " - " ~ title %}
      {% if page.parent.parent is not none %}
        {% set title = page.parent.parent.title ~ " - " ~ title %}
      {% endif %}
    {% endif %}
    {% if page and page.meta and page.meta.title %}
      {% set title = page.meta.title ~ " - " ~ title %}
    {% elif page and page.title and not page.is_homepage %}
      {% set title = page.title | striptags ~ " - " ~ title %}
    {% endif %}
    x{{ title }}

  - &page_description >-
    {{ page.meta.get("description", config.site_description) or "" }}

tags:
  title: *page_title_with_site_name
  description: *page_description